### ISSUE TITLE
1-based pagination seems so far away

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/the-funky-knowledge-base#13]
![image](https://user-images.githubusercontent.com/5226627/59967371-b234d180-94dd-11e9-845b-82d949ee8425.png)

Is this why the cool kids do not use Liquid templates? 👇 

```liquid
permalink: different/page-{{ pagination.pageNumber + 1 }}/index.html
```
https://www.11ty.io/docs/pagination/

also, this is supposed to be the last page:
![image](https://user-images.githubusercontent.com/5226627/59967350-8ca7c800-94dd-11e9-8bd5-9b5dcdb6266b.png)

**Comment by BryanWilhite** [comment]
okay i am switching to [nunjucks](https://mozilla.github.io/nunjucks/templating.html) 🐰 🕳 

- [ ] change `assign` to `set`
- [ ] replace `case` with `if` expressions [[docs](https://mozilla.github.io/nunjucks/templating.html#if-expression)]

**Comment by BryanWilhite** [comment]
getting this wonderful 🐰 🕳

```console
Error writing templates: (more in DEBUG output)
> Having trouble writing template: docs/entry/kb2076072072/index.html (TemplateWriterWriteError)
> (unknown path) [Line 41, Column 59]
  expected variable end (Template render error):
    Template render error: (unknown path) [Line 41, Column 59]
      expected variable end
        at Object._prettifyError (E:\~shares\sourceRoot\the-funky-knowledge-base\node_modules\nunjucks\src\lib.js:36:11)
        at Template.render (E:\~shares\sourceRoot\the-funky-knowledge-base\node_modules\nunjucks\src\environment.js:542:21)
        at E:\~shares\sourceRoot\the-funky-knowledge-base\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:136:14
        at new Promise (<anonymous>)
        at E:\~shares\sourceRoot\the-funky-knowledge-base\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:135:14
        at TemplateLayout.render (E:\~shares\sourceRoot\the-funky-knowledge-base\node_modules\@11ty\eleventy\src\TemplateLayout.js:135:31)
        at process._tickCallback (internal/process/next_tick.js:68:7)
Copied 2 items and Processed 0 files in 5.40 seconds
```

**Comment by BryanWilhite** [comment]
this `Having trouble writing template` error _feels_ like Nunjucks is way, _way_ more ‘sensitive’ 🐇  and grumpy than ‘small, dumb’ liquid; to avoid a serious case of 🐰 🕳 i am going to roll back to liquid and be curious about handlebars

**Comment by BryanWilhite** [comment]
looking at liquid again 👀 
- liquid _has_ [math filters](https://help.shopify.com/en/themes/liquid/filters/math-filters): just use `{{ pageNumber | plus: 1 }}`
- just use `default_pagination` [[docs]({{ paginate | default_pagination }})]

**Comment by BryanWilhite** [comment]
![image](https://user-images.githubusercontent.com/5226627/59970569-5474a980-951e-11e9-8584-5c5fe592569b.png)

![image](https://user-images.githubusercontent.com/5226627/59970571-66eee300-951e-11e9-94a6-434d905446c8.png)

![image](https://user-images.githubusercontent.com/5226627/59970572-74a46880-951e-11e9-972a-1dd00fff3e09.png)

![image](https://user-images.githubusercontent.com/5226627/59970573-7e2dd080-951e-11e9-91fb-ffb1958cfcd1.png)
