### ISSUE TITLE
convert legacy JSON to markdown

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/the-funky-knowledge-base#7]
not sure whether a `dotnet` console app or Node scripting will be the way to go

**Comment by BryanWilhite** [comment]
a `dotnet` test app under a `dotnet/` folder is the fastest way to go (for me) ☂️ ☔️

**Comment by BryanWilhite** [comment]
ran into this problem while doing something as simple as `dotnet restore`: https://medium.com/codebase/unable-to-obtain-lock-file-access-dotnet-cli-3bd313a5009c

**Comment by BryanWilhite** [comment]
i am currently curious about the use of JSON front matter for liquid `*.md` files; when this is not possible then this article suggests that `YamlDotNet` and `Markdig` is the way to go:

https://markheath.net/post/markdown-html-yaml-front-matter

**Comment by BryanWilhite** [comment]
JSON in the markdown appears to be supported (based on results in the last push):

```md
---json
{
  "title": "My page title"
}
---

Welcome to my new blog! Here is a list:

- one
- two
- three
```

**Comment by BryanWilhite** [comment]
Newtonsoft.Json 12.02 cannot parse escaped characters in JSON strings on .NET Core; i arrogantly assume that @JamesNK does not have the time to investigate the validity of my statement

```console
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (64-bit .NET Core 4.6.27617.04)
[xUnit.net 00:00:00.50]   Discovering: Songhay.Publications.Tests
[xUnit.net 00:00:00.62]   Discovered:  Songhay.Publications.Tests
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (64-bit .NET Core 4.6.27617.04)
[xUnit.net 00:00:00.54]   Starting:    Songhay.Publications.Tests
[xUnit.net 00:00:00.78]     Songhay.Publications.Tests.FunkyKBTests.ShouldLoadEntry(entryInfo: ..\the-funky-knowledge-base\_data\kb\entries\kb904850341.json, mdInfo: ..\the-funky-knowledge-base\posts\kb904850341.md) [FAIL]
[xUnit.net 00:00:00.78]       Newtonsoft.Json.JsonReaderException : After parsing a value an unexpected character was encountered: C. Path 'title', line 1, position 47.
[xUnit.net 00:00:00.78]       Stack Trace:
[xUnit.net 00:00:00.78]            at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
[xUnit.net 00:00:00.78]            at Newtonsoft.Json.JsonTextReader.Read()
[xUnit.net 00:00:00.78]            at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
[xUnit.net 00:00:00.78]            at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
[xUnit.net 00:00:00.78]            at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
[xUnit.net 00:00:00.78]            at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
[xUnit.net 00:00:00.78]         ..\the-funky-knowledge-base\shell\Songhay.Publications.Tests\FunkyKBTests.cs(77,0): at Songhay.Publications.Tests.FunkyKBTests.GetMarkdown(JObject input)
[xUnit.net 00:00:00.78]         ..\the-funky-knowledge-base\shell\Songhay.Publications.Tests\FunkyKBTests.cs(52,0): at Songhay.Publications.Tests.FunkyKBTests.ShouldLoadEntry(FileInfo entryInfo, FileInfo mdInfo)
[xUnit.net 00:00:00.79]   Finished:    Songhay.Publications.Tests
----- Test Execution Summary -----

Songhay.Publications.Tests.FunkyKBTests.ShouldLoadEntry:
    Outcome: Failed
    Error Message:
    Newtonsoft.Json.JsonReaderException : After parsing a value an unexpected character was encountered: C. Path 'title', line 1, position 47.
    Stack Trace:
       at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Songhay.Publications.Tests.FunkyKBTests.GetMarkdown(JObject input) in ..\the-funky-knowledge-base\shell\Songhay.Publications.Tests\FunkyKBTests.cs:line 77
   at Songhay.Publications.Tests.FunkyKBTests.ShouldLoadEntry(FileInfo entryInfo, FileInfo mdInfo) in ..\the-funky-knowledge-base\shell\Songhay.Publications.Tests\FunkyKBTests.cs:line 52
    
Total tests: 1. Passed: 0. Failed: 1. Skipped: 0
```

Source JSON (UTF-8):

```JSON
{
  "Document": {
    "DocumentId": 904850341,
    "Title": "PROBLEM: \"Can't Execute a Non-Action Query\" Error with Pass-Through Queries",
    "DocumentShortName": null,
    "FileName": null,
    "Path": null,
    "CreateDate": "1998-09-03T12:19:21",
    "ModificationDate": "1998-09-03T12:19:21",
    "TemplateId": null,
    "SegmentId": 63,
    "IsRoot": false,
    "IsActive": true,
    "SortOrdinal": null,
    "ClientId": null,
    "Tag": null
  },
  "Content": "A compiled Pass-Through Query in the QueryDefs collection of a DAO database can be referenced in code like the following:\n\n    Set qdDAO = dbDAO.QueryDefs(\"qsptTaz3Test00\")\n    qdDAO.Execute DB_FAILONERROR\n\nwhere \"qsptTaz3Test00\" is the name of the compiled Pass-Through query and \"qdDAO\" is the name of a QueryDef object. Calling the Execute method of the QueryDef object may generate the error, \"Can't Execute a Non-Action Query.\" This error will occur when the Returns Records property of the Pass-Through query is set to Yes.\n\nNote: multiple SQL commands can be placed in an Access Pass-Through query but it is not recommended to mix select statements with SQL that does not return records like update statements.",
  "Tag": "kb904850341"
}
```
